.TH FEM 1 "2 May 24"
.SH NAME
fem - fast editor machine for feminizing and transforming input
.SH SYNOPSIS
\fBfem\fP [ -V ] [ --version ] [ -f ] [ --force ] [ -r ] [ --reverse ]
.SH DESCRIPTION
\fBfem\fP takes in arbitrary input and feminizes it.
.SS Options
.TP
\fB--version\fP, \fB-V\fP
Output version information and exit.
.TP
\fB--force\fP, \fB-f\fP
Forcefully feminizes the input, even if it does not comply. To be used with caution, as it can cause lasting harm.
.TP
\fB--reverse\fP, \fB-r\fP
Reverses a previous feminization. May also be used to perform a masculinization on non-feminized feminine input,
although that mode of operation has not yet been tested.
.SH "SEE ALSO"
rustc(1)
.SH BUGS
No known bugs.
